[project]
name = "babel-validation"
version = "0.1.0"
description = "A set of programs for validating the output of the Babel pipelines."
license = "MIT"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "black>=25.9.0",
    "deepdiff>=8.6.1",
    "openapi-spec-validator>=0.7.2",
    "pytest>=8.4.2",
    "requests>=2.32.5",
]

[project.urls]
Repository = "https://github.com/TranslatorSRI/babel-validation"
